import { Product } from '../types/Product';

export const produtos: Product[] = [
  {
    id: 'p1',
    nome: 'Picolé Le Petit Tuti Frutti',
    custo: 1.56,
    caixaQt: 36,
    sugestao: 2.25,
    caixa: true,
    familia: 'f1',
  },
  { id: 'p2', nome: 'Picolé Le Petit Groselha', custo: 1.56, caixaQt: 36, sugestao: 2.25, caixa: true, familia: 'f1' },
  { id: 'p3', nome: 'Picolé Le Petit Chocolate', custo: 1.56, caixaQt: 36, sugestao: 2.25, caixa: true, familia: 'f1' },
  {
    id: 'p4',
    nome: 'Picolé Le Petit Chocolate Branco',
    custo: 1.56,
    caixaQt: 36,
    sugestao: 2.25,
    caixa: true,
    familia: 'f1',
  },
  {
    id: 'p6',
    nome: 'Picolé Di Drill Churros Brigadeiro',
    custo: 2.61,
    caixaQt: 24,
    sugestao: 3.75,
    caixa: true,
    familia: 'f2',
  },
  {
    id: 'p7',
    nome: 'Picolé Di Drill Churros Doce de leite',
    custo: 2.61,
    caixaQt: 24,
    sugestao: 3.75,
    caixa: true,
    familia: 'f2',
  },
  { id: 'p9', nome: 'Picolé Di Fruta Abacaxi', custo: 2.09, caixaQt: 28, sugestao: 3, caixa: true, familia: 'f3' },
  { id: 'p10', nome: 'Picolé Di Fruta Limão', custo: 2.09, caixaQt: 28, sugestao: 3, caixa: true, familia: 'f3' },
  { id: 'p11', nome: 'Picolé Di Fruta Maracujá', custo: 2.09, caixaQt: 28, sugestao: 3, caixa: true, familia: 'f3' },
  { id: 'p12', nome: 'Picolé Di Fruta Uva', custo: 2.09, caixaQt: 28, sugestao: 3, caixa: true, familia: 'f3' },
  { id: 'p14', nome: 'Picolé Di Leite Chocolate', custo: 2.45, caixaQt: 28, sugestao: 3.5, caixa: true, familia: 'f4' },
  { id: 'p15', nome: 'Picolé Di Leite Coco', custo: 2.45, caixaQt: 28, sugestao: 3.5, caixa: true, familia: 'f4' },
  {
    id: 'p17',
    nome: 'Picolé Di Leite Limonada Suiça',
    custo: 2.45,
    caixaQt: 28,
    sugestao: 3.5,
    caixa: true,
    familia: 'f4',
  },
  {
    id: 'p18',
    nome: 'Picolé Di Leite Milho Verde',
    custo: 2.45,
    caixaQt: 28,
    sugestao: 3.5,
    caixa: true,
    familia: 'f4',
  },
  { id: 'p19', nome: 'Picolé Di Leite Morango', custo: 2.45, caixaQt: 28, sugestao: 3.5, caixa: true, familia: 'f4' },
  // {
  //   id: 'p21',
  //   nome: 'Picolé Especialité Beijinho',
  //   custo: 4.58,
  //   caixaQt: 26,
  //   sugestao: 6.5,
  //   caixa: true,
  //   familia: 'f5',
  // },
  {
    id: 'p22',
    nome: 'Picolé Especialité Morango recheado',
    custo: 4.58,
    caixaQt: 26,
    sugestao: 6.5,
    caixa: true,
    familia: 'f5',
  },
  {
    id: 'p23',
    nome: 'Picolé Especialité Brigadeiro Chocolate',
    custo: 4.58,
    caixaQt: 24,
    sugestao: 6.5,
    caixa: true,
    familia: 'f5',
  },
  {
    id: 'p24',
    nome: 'Picolé Especialité Brigadeiro Morango',
    custo: 4.58,
    caixaQt: 24,
    sugestao: 6.5,
    caixa: true,
    familia: 'f5',
  },
  {
    id: 'p25',
    nome: 'Picolé Especialité Tablets',
    custo: 4.58,
    caixaQt: 26,
    sugestao: 6.5,
    caixa: true,
    familia: 'f5',
  },
  {
    id: 'p26',
    nome: 'Picolé Especialité Vivotello',
    custo: 4.58,
    caixaQt: 24,
    sugestao: 6.5,
    caixa: true,
    familia: 'f5',
  },
  { id: 'p28', nome: 'Paleta Leite Trufado', custo: 6.39, caixaQt: 14, sugestao: 9, caixa: true, familia: 'f6' },
  {
    id: 'p29',
    nome: 'Paleta Morango c/ Leite Condensado',
    custo: 6.39,
    caixaQt: 14,
    sugestao: 9,
    caixa: true,
    familia: 'f6',
  },
  { id: 'p31', nome: 'Extrusado Absoluto Avelã', custo: 5.64, caixaQt: 20, sugestao: 8, caixa: true, familia: 'f7' },
  {
    id: 'p32',
    nome: 'Extrusado Absoluto Avelã ao Leite',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f7',
  },
  {
    id: 'p33',
    nome: 'Extrusado Absoluto Chocolate Trufado',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f7',
  },
  {
    id: 'p34',
    nome: 'Extrusado Absoluto Iogurte c/ Amarena',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f7',
  },
  {
    id: 'p35',
    nome: 'Extrusado Absoluto Petit Gateau',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f7',
  },
  {
    id: 'p36',
    nome: 'Extrusado Absoluto Torta de Limão',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f7',
  },
  { id: 'p38', nome: 'Extrusado Classic Cookies', custo: 5.64, caixaQt: 20, sugestao: 8, caixa: true, familia: 'f8' },
  {
    id: 'p39',
    nome: 'Extrusado Classic Chococolate',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f8',
  },
  {
    id: 'p40',
    nome: 'Extrusado Classic Chocolate Branco',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f8',
  },
  {
    id: 'p41',
    nome: 'Extrusado Classic Chocolate Meio Amargo',
    custo: 5.64,
    caixaQt: 20,
    sugestao: 8,
    caixa: true,
    familia: 'f8',
  },
  // { id: 'p42', nome: 'Extrusado Classic Trufa', custo: 5.64, caixaQt: 20, sugestao: 8, caixa: true, familia: 'f8' },
  { id: 'p43', nome: 'Extrusado Classic Vivolak', custo: 5.64, caixaQt: 20, sugestao: 8, caixa: true, familia: 'f8' },
  {
    id: 'p45',
    nome: 'Extrusado Di Açaí C/ Guaraná',
    custo: 3.86,
    caixaQt: 20,
    sugestao: 5.5,
    caixa: true,
    familia: 'f9',
  },
  {
    id: 'p47',
    nome: 'Extrusado Premiatto Napolitano',
    custo: 3.86,
    caixaQt: 20,
    sugestao: 5.5,
    caixa: true,
    familia: 'f10',
  },
  {
    id: 'p48',
    nome: 'Extrusado Premiatto Vivotella',
    custo: 3.86,
    caixaQt: 20,
    sugestao: 5.5,
    caixa: true,
    familia: 'f10',
  },
  {
    id: 'p50',
    nome: 'Extrusado Mini Pé Moleque Preto',
    custo: 4.22,
    caixaQt: 20,
    sugestao: 6,
    caixa: true,
    familia: 'f11',
  },
  { id: 'p51', nome: 'Extrusado Mini Skimo', custo: 4.22, caixaQt: 20, sugestao: 6, caixa: true, familia: 'f11' },
  {
    id: 'p53',
    nome: 'Extrusado Di infantil Algodão Doce',
    custo: 2.98,
    caixaQt: 20,
    sugestao: 4.25,
    caixa: true,
    familia: 'f12',
  },
  { id: 'p55', nome: 'Cone Divine Biscoito', custo: 5.78, caixaQt: 16, sugestao: 8.25, caixa: true, familia: 'f13' },
  {
    id: 'p56',
    nome: 'Cone Divine Black and White',
    custo: 5.78,
    caixaQt: 16,
    sugestao: 8.25,
    caixa: true,
    familia: 'f13',
  },
  { id: 'p57', nome: 'Cone Divine Brigadeiro', custo: 5.78, caixaQt: 16, sugestao: 8.25, caixa: true, familia: 'f13' },
  { id: 'p58', nome: 'Cone Divine Crocante', custo: 5.78, caixaQt: 16, sugestao: 8.25, caixa: true, familia: 'f13' },
  {
    id: 'p59',
    nome: 'Cone Divine Leite Trufado',
    custo: 5.78,
    caixaQt: 16,
    sugestao: 8.25,
    caixa: true,
    familia: 'f13',
  },
  { id: 'p61', nome: 'Sundae Nata/Chocolate', custo: 4.48, caixaQt: 8, sugestao: 6, caixa: true, familia: 'f14' },
  { id: 'p62', nome: 'Sundae Nata/Morango', custo: 4.48, caixaQt: 8, sugestao: 6, caixa: true, familia: 'f14' },
  { id: 'p64', nome: 'Copo 400ml Abacaxi ao Vinho', custo: 6.6, caixaQt: 12, sugestao: 9, caixa: true, familia: 'f15' },
  { id: 'p65', nome: 'Copo 400ml Bombom', custo: 6.6, caixaQt: 12, sugestao: 9, caixa: true, familia: 'f15' },
  { id: 'p66', nome: 'Copo 400ml Brigadeiro', custo: 6.6, caixaQt: 12, sugestao: 9, caixa: true, familia: 'f15' },
  { id: 'p67', nome: 'Copo 400ml Flocos', custo: 6.6, caixaQt: 12, sugestao: 9, caixa: true, familia: 'f15' },
  { id: 'p68', nome: 'Copo 400ml Napolitano', custo: 6.6, caixaQt: 12, sugestao: 9, caixa: true, familia: 'f15' },
  { id: 'p70', nome: 'Splendido Nata/Chocolate', custo: 7.02, caixaQt: 12, sugestao: 9.5, caixa: true, familia: 'f16' },
  { id: 'p71', nome: 'Splendido Nata/Morango', custo: 7.02, caixaQt: 12, sugestao: 9.5, caixa: true, familia: 'f16' },
  {
    id: 'p73',
    nome: 'Pote 1,020lts Açaí c/ Leitinho',
    custo: 22.78,
    caixaQt: 6,
    sugestao: 29,
    caixa: false,
    familia: 'f17',
  },
  {
    id: 'p74',
    nome: 'Pote 1,020lts Açaí c/ Avelã',
    custo: 22.78,
    caixaQt: 6,
    sugestao: 29,
    caixa: false,
    familia: 'f17',
  },
  {
    id: 'p76',
    nome: 'PT 1,5lts Frutas Vermelhas',
    custo: 14.76,
    caixaQt: 4,
    sugestao: 20,
    caixa: false,
    familia: 'f18',
  },
  { id: 'p77', nome: 'PT 1,5lts Manga', custo: 14.76, caixaQt: 4, sugestao: 20, caixa: false, familia: 'f18' },
  {
    id: 'p79',
    nome: 'PT 1,8 LTS Splendido Abacaxi c/ Abacaxi',
    custo: 24.05,
    caixaQt: 2,
    sugestao: 31.99,
    caixa: true,
    familia: 'f19',
  },
  // {
  //   id: 'p80',
  //   nome: 'PT 1,8 LTS Splendido Cheesecake Goiaba',
  //   custo: 24.05,
  //   caixaQt: 2,
  //   sugestao: 31.99,
  //   caixa: true,
  //   familia: 'f19',
  // },
  {
    id: 'p81',
    nome: 'PT 1,8 LTS Splendido Choc branco/ choc ao leite',
    custo: 24.05,
    caixaQt: 2,
    sugestao: 31.99,
    caixa: true,
    familia: 'f19',
  },
  {
    id: 'p82',
    nome: 'PT 1,8LTS Splendido Iogurte / Frutas vermelhas',
    custo: 24.05,
    caixaQt: 2,
    sugestao: 31.99,
    caixa: true,
    familia: 'f19',
  },
  {
    id: 'p97',
    nome: 'PT 1,8LTS Splendido Iogurte / Maracujá',
    custo: 24.05,
    caixaQt: 2,
    sugestao: 31.99,
    caixa: true,
    familia: 'f19',
  },
  // {
  //   id: 'p83',
  //   nome: 'PT 1,8LTS Splendido Leite condensado c/ limão',
  //   custo: 24.05,
  //   caixaQt: 2,
  //   sugestao: 31.99,
  //   caixa: true,
  //   familia: 'f19',
  // },
  {
    id: 'p84',
    nome: 'PT 1,8 LTS Splendido Leite Trufado',
    custo: 24.05,
    caixaQt: 2,
    sugestao: 31.99,
    caixa: true,
    familia: 'f19',
  },
  {
    id: 'p85',
    nome: 'PT 1,8 LTS Splendido Morango ao Leite',
    custo: 24.05,
    caixaQt: 2,
    sugestao: 31.99,
    caixa: true,
    familia: 'f19',
  },
  {
    id: 'p87',
    nome: 'PT 2LTS Abacaxi ao Vinho',
    custo: 21.52,
    caixaQt: 8,
    sugestao: 28.99,
    caixa: false,
    familia: 'f20',
  },
  // {
  //   id: 'p88',
  //   nome: 'PT 2LTS Abacaxi / Leitinho',
  //   custo: 21.52,
  //   caixaQt: 8,
  //   sugestao: 28.99,
  //   caixa: false,
  //   familia: 'f20',
  // },
  { id: 'p89', nome: 'PT 2LTS Bombom', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
  { id: 'p90', nome: 'PT 2LTS Brigadeiro', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
  { id: 'p91', nome: 'PT 2LTS Chocolate', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
  { id: 'p92', nome: 'PT 2LTS Creme', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
  { id: 'p93', nome: 'PT 2LTS Flocos', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
  {
    id: 'p94',
    nome: 'PT 2LTS Grego Tradicional',
    custo: 21.52,
    caixaQt: 8,
    sugestao: 28.99,
    caixa: false,
    familia: 'f20',
  },
  { id: 'p95', nome: 'PT 2LTS Morango', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
  { id: 'p96', nome: 'PT 2LTS Napolitano', custo: 21.52, caixaQt: 8, sugestao: 28.99, caixa: false, familia: 'f20' },
];
