import { Product } from '../types/Product';

export const produtos: Product[] = [
  {
    id: '1',
    nome: 'Picolé Le Petit Tuti Frutti',
    custo: 1.39,
    caixaQt: 36,
    sugestao: 2,
    caixa: true,
    familia: 'Le petit',
  },
  {
    id: '2',
    nome: 'Picolé Le Petit Groselha',
    custo: 1.39,
    caixaQt: 36,
    sugestao: 2,
    caixa: true,
    familia: 'Le petit',
  },
  {
    id: '3',
    nome: 'Picolé Le Petit Chocolate',
    custo: 1.39,
    caixaQt: 36,
    sugestao: 2,
    caixa: true,
    familia: 'Le petit',
  },
  {
    id: '4',
    nome: 'Picolé Le Petit Chocolate Branco',
    custo: 1.39,
    caixaQt: 36,
    sugestao: 2,
    caixa: true,
    familia: 'Le petit',
  },
  {
    id: '6',
    nome: 'Picolé Di Drill Churros Brigadeiro',
    custo: 2.09,
    caixaQt: 24,
    sugestao: 3,
    caixa: true,
    familia: 'Di Drill',
  },
  {
    id: '7',
    nome: 'Picolé Di Drill Churros Doce de leite',
    custo: 2.09,
    caixaQt: 24,
    sugestao: 3,
    caixa: true,
    familia: 'Di Drill',
  },
  {
    id: '9',
    nome: 'Picolé Di Fruta Abacaxi',
    custo: 1.74,
    caixaQt: 28,
    sugestao: 2.5,
    caixa: true,
    familia: 'Di Fruti',
  },
  { id: '10', nome: 'Picolé Di FrutaLimão', custo: 1.74, caixaQt: 28, sugestao: 2.5, caixa: true, familia: 'Di Fruti' },
  {
    id: '11',
    nome: 'Picolé Di Fruta Maracujá',
    custo: 1.74,
    caixaQt: 28,
    sugestao: 2.5,
    caixa: true,
    familia: 'Di Fruti',
  },
  { id: '12', nome: 'Picolé Di Fruta Uva', custo: 1.74, caixaQt: 28, sugestao: 2.5, caixa: true, familia: 'Di Fruti' },
  {
    id: '14',
    nome: 'Picolé Di Leite Chocolate',
    custo: 2.27,
    caixaQt: 28,
    sugestao: 3.25,
    caixa: true,
    familia: 'Di Leiti',
  },
  {
    id: '15',
    nome: 'Picolé Di Leite Coco',
    custo: 2.27,
    caixaQt: 28,
    sugestao: 3.25,
    caixa: true,
    familia: 'Di Leiti',
  },
  {
    id: '16',
    nome: 'Picolé Di Leite Leite Condensado',
    custo: 2.27,
    caixaQt: 28,
    sugestao: 3.25,
    caixa: true,
    familia: 'Di Leiti',
  },
  {
    id: '17',
    nome: 'Picolé Di Leite Limonada Suiça',
    custo: 2.27,
    caixaQt: 28,
    sugestao: 3.25,
    caixa: true,
    familia: 'Di Leiti',
  },
  {
    id: '18',
    nome: 'Picolé Di Leite Milho Verde',
    custo: 2.27,
    caixaQt: 28,
    sugestao: 3.25,
    caixa: true,
    familia: 'Di Leiti',
  },
  {
    id: '19',
    nome: 'Picolé Di Morango Morango',
    custo: 2.27,
    caixaQt: 28,
    sugestao: 3.25,
    caixa: true,
    familia: 'Di Leiti',
  },
  {
    id: '21',
    nome: 'Picolé Especialité Morango recheado',
    custo: 4.23,
    caixaQt: 26,
    sugestao: 6,
    caixa: true,
    familia: 'Especialité',
  },
  {
    id: '22',
    nome: 'Picolé Especialité Brigadeiro Chocolate',
    custo: 4.23,
    caixaQt: 24,
    sugestao: 6,
    caixa: true,
    familia: 'Especialité',
  },
  {
    id: '23',
    nome: 'Picolé Esopecialité Brigadeiro Morango',
    custo: 4.23,
    caixaQt: 24,
    sugestao: 6,
    caixa: true,
    familia: 'Especialité',
  },
  {
    id: '24',
    nome: 'Picolé Especialité Tablets',
    custo: 4.23,
    caixaQt: 26,
    sugestao: 6,
    caixa: true,
    familia: 'Especialité',
  },
  {
    id: '25',
    nome: 'Picolé Especialité Vivotello',
    custo: 4.23,
    caixaQt: 26,
    sugestao: 6,
    caixa: true,
    familia: 'Especialité',
  },
  {
    id: '27',
    nome: 'Paleta Leite Trufado',
    custo: 5.68,
    caixaQt: 14,
    sugestao: 8,
    caixa: true,
    familia: 'Paletas Mexicanas',
  },
  {
    id: '28',
    nome: 'Paleta Morango c/ Leite Condensado',
    custo: 5.68,
    caixaQt: 14,
    sugestao: 8,
    caixa: true,
    familia: 'Paletas Mexicanas',
  },
  {
    id: '30',
    nome: 'Extrusado Absoluto Avelã',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Absoluto',
  },
  {
    id: '31',
    nome: 'Extrusado Absoluto Avelã ao Leite',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Absoluto',
  },
  {
    id: '32',
    nome: 'Extrusado Absoluto Chocolate Trufado',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Absoluto',
  },
  {
    id: '33',
    nome: 'Extrusado Absoluto Iogurte c/ Amarena',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Absoluto',
  },
  {
    id: '34',
    nome: 'Extrusado Absoluto Petit Gateau',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Absoluto',
  },
  {
    id: '35',
    nome: 'Extrusado Absoluto Torta de Limão',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Absoluto',
  },
  {
    id: '37',
    nome: 'Extrusado Classic Cookies',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Classic',
  },
  {
    id: '38',
    nome: 'Extrusado Classic Chococolate',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Classic',
  },
  {
    id: '39',
    nome: 'Extrusado Classic Chocolate Branco',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Classic',
  },
  {
    id: '40',
    nome: 'Extrusado Classic Chocolate Meio Amargo',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Classic',
  },
  {
    id: '41',
    nome: 'Extrusado Classic Vivolak',
    custo: 5.11,
    caixaQt: 20,
    sugestao: 7.25,
    caixa: true,
    familia: 'Extrusado Classic',
  },
  {
    id: '43',
    nome: 'Extrusado Di Açaí C/ Guaraná',
    custo: 3.51,
    caixaQt: 20,
    sugestao: 5,
    caixa: true,
    familia: 'Di Açaí',
  },
  {
    id: '45',
    nome: 'Extrusado Premiatto Napolitano',
    custo: 3.51,
    caixaQt: 20,
    sugestao: 5,
    caixa: true,
    familia: 'Extrusados Premiatto',
  },
  {
    id: '46',
    nome: 'Extrusado Premiatto Vivotella',
    custo: 3.51,
    caixaQt: 20,
    sugestao: 5,
    caixa: true,
    familia: 'Extrusados Premiatto',
  },
  {
    id: '48',
    nome: 'Extrusado Mini Pé Moleque Preto',
    custo: 3.87,
    caixaQt: 20,
    sugestao: 5.5,
    caixa: true,
    familia: 'Mini Extrusado',
  },
  {
    id: '49',
    nome: 'Extrusado Mini Skimo',
    custo: 3.87,
    caixaQt: 20,
    sugestao: 5.5,
    caixa: true,
    familia: 'Mini Extrusado',
  },
  {
    id: '51',
    nome: 'Extrusado Di infantil Algodão Doce',
    custo: 2.63,
    caixaQt: 20,
    sugestao: 3.75,
    caixa: true,
    familia: 'Di Infantil',
  },
  {
    id: '53',
    nome: 'Cone Divine Biscoito',
    custo: 5.25,
    caixaQt: 16,
    sugestao: 7.5,
    caixa: true,
    familia: 'Cones Divine',
  },
  {
    id: '54',
    nome: 'Cone Divine Black and White',
    custo: 5.25,
    caixaQt: 16,
    sugestao: 7.5,
    caixa: true,
    familia: 'Cones Divine',
  },
  {
    id: '55',
    nome: 'Cone Divine Brigadeiro',
    custo: 5.25,
    caixaQt: 16,
    sugestao: 7.5,
    caixa: true,
    familia: 'Cones Divine',
  },
  {
    id: '56',
    nome: 'Cone Divine Crocante',
    custo: 5.25,
    caixaQt: 16,
    sugestao: 7.5,
    caixa: true,
    familia: 'Cones Divine',
  },
  {
    id: '57',
    nome: 'Cone Divine Leite Trufado',
    custo: 5.25,
    caixaQt: 16,
    sugestao: 7.5,
    caixa: true,
    familia: 'Cones Divine',
  },
  { id: '59', nome: 'Sundae Nata/Chocolate', custo: 4.11, caixaQt: 8, sugestao: 5.5, caixa: true, familia: 'Sundae' },
  { id: '60', nome: 'Sundae Nata/Morango', custo: 4.11, caixaQt: 8, sugestao: 5.5, caixa: true, familia: 'Sundae' },
  {
    id: '62',
    nome: 'Copo 400ml Abacaxi ao Vinho',
    custo: 5.87,
    caixaQt: 12,
    sugestao: 8,
    caixa: true,
    familia: 'Copão 400Ml',
  },
  { id: '63', nome: 'Copo 400ml Bombom', custo: 5.87, caixaQt: 12, sugestao: 8, caixa: true, familia: 'Copão 400Ml' },
  {
    id: '64',
    nome: 'Copo 400ml Brigadeiro',
    custo: 5.87,
    caixaQt: 12,
    sugestao: 8,
    caixa: true,
    familia: 'Copão 400Ml',
  },
  { id: '65', nome: 'Copo 400ml Flocos', custo: 5.87, caixaQt: 12, sugestao: 8, caixa: true, familia: 'Copão 400Ml' },
  {
    id: '66',
    nome: 'Copo 400ml Napolitano',
    custo: 5.87,
    caixaQt: 12,
    sugestao: 8,
    caixa: true,
    familia: 'Copão 400Ml',
  },
  {
    id: '68',
    nome: 'Splendido Nata/Chocolate',
    custo: 6.28,
    caixaQt: 12,
    sugestao: 8.5,
    caixa: true,
    familia: 'Copo 400ml Splendido',
  },
  {
    id: '69',
    nome: 'Splendido Nata/Morango',
    custo: 6.28,
    caixaQt: 12,
    sugestao: 8.5,
    caixa: true,
    familia: 'Copo 400ml Splendido',
  },
  {
    id: '71',
    nome: 'Pote 1,020lts Açaí c/ Leitinho',
    custo: 22.78,
    caixaQt: 6,
    sugestao: 29,
    caixa: true,
    familia: 'Potes 1,0 Litros Gormet',
  },
  {
    id: '72',
    nome: 'Pote 1,020lts Açaí c/ Trufado',
    custo: 22.78,
    caixaQt: 6,
    sugestao: 29,
    caixa: true,
    familia: 'Potes 1,0 Litros Gormet',
  },
  {
    id: '74',
    nome: 'PT 1,5lts Frutas Vermelhas',
    custo: 14.76,
    caixaQt: 4,
    sugestao: 20,
    caixa: true,
    familia: 'Potes 1,5 Litros Sorbet',
  },
  {
    id: '75',
    nome: 'PT 1,5lts Graviola',
    custo: 14.76,
    caixaQt: 4,
    sugestao: 20,
    caixa: true,
    familia: 'Potes 1,5 Litros Sorbet',
  },
  {
    id: '76',
    nome: 'PT 1,5lts Manga',
    custo: 14.76,
    caixaQt: 4,
    sugestao: 20,
    caixa: true,
    familia: 'Potes 1,5 Litros Sorbet',
  },
  {
    id: '78',
    nome: 'PT 1,8 LTS Splendido Abacaxi c/ Abacaxi',
    custo: 23.3,
    caixaQt: 2,
    sugestao: 31,
    caixa: true,
    familia: 'Potes 1,8 Litros',
  },
  {
    id: '79',
    nome: 'PT 1,8 LTS Splendido Coco c/ Brigadeiro',
    custo: 23.3,
    caixaQt: 2,
    sugestao: 31,
    caixa: true,
    familia: 'Potes 1,8 Litros',
  },
  {
    id: '80',
    nome: 'PT 1,8 LTS Splendido Choc branco/ choc ao leite',
    custo: 23.3,
    caixaQt: 2,
    sugestao: 31,
    caixa: true,
    familia: 'Potes 1,8 Litros',
  },
  {
    id: '81',
    nome: 'PT 1,8LTS Splendido Iogurte / Frutas vermelhas',
    custo: 23.3,
    caixaQt: 2,
    sugestao: 31,
    caixa: true,
    familia: 'Potes 1,8 Litros',
  },
  {
    id: '82',
    nome: 'PT 1,8 LTS Splendido Leite Trufado',
    custo: 23.3,
    caixaQt: 2,
    sugestao: 31,
    caixa: true,
    familia: 'Potes 1,8 Litros',
  },
  {
    id: '83',
    nome: 'PT 1,8 LTS Splendido Morango ao Leite',
    custo: 23.3,
    caixaQt: 2,
    sugestao: 31,
    caixa: true,
    familia: 'Potes 1,8 Litros',
  },
  {
    id: '85',
    nome: 'PT 2LTS Abacaxi ao Vinho',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '86',
    nome: 'PT 2LTS Bombom',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '87',
    nome: 'PT 2LTS Brigadeiro',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '88',
    nome: 'PT 2LTS Chocolate',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '89',
    nome: 'PT 2LTS Creme',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '90',
    nome: 'PT 2LTS Flocos',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '91',
    nome: 'PT 2LTS Grego Tradicional',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '92',
    nome: 'PT 2LTS Morango',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '93',
    nome: 'PT 2LTS Napolitano',
    custo: 20.78,
    caixaQt: 8,
    sugestao: 28,
    caixa: false,
    familia: 'Potes 2,0 Litros',
  },
  {
    id: '95',
    nome: 'PT 7LTS Abacaxi ao Vinho',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  {
    id: '96',
    nome: 'PT 7LTS Bombom',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  {
    id: '97',
    nome: 'PT 7LTS Brigadeiro',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  {
    id: '98',
    nome: 'PT 7LTS Chocolate',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  { id: '99', nome: 'PT 7LTS Creme', custo: 64.62, caixaQt: 1, sugestao: 85, caixa: true, familia: 'Potes 7,0 Litros' },
  {
    id: '100',
    nome: 'PT 7LTS Flocos',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  {
    id: '101',
    nome: 'PT 7LTS Grego Tradicional',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  {
    id: '102',
    nome: 'PT 7LTS Morango',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
  {
    id: '103',
    nome: 'PT 7LTS Napolitano',
    custo: 64.62,
    caixaQt: 1,
    sugestao: 85,
    caixa: true,
    familia: 'Potes 7,0 Litros',
  },
];
